set(ILLIXR_GEMMINI_PACKING "scalar" CACHE STRING "Gemmini packing implementation: scalar or rvv")
set_property(CACHE ILLIXR_GEMMINI_PACKING PROPERTY STRINGS scalar rvv)
set(ILLIXR_GEMMINI_PACKING_TRAVERSAL "rows" CACHE STRING "RVV packing traversal: rows or contiguous")
set_property(CACHE ILLIXR_GEMMINI_PACKING_TRAVERSAL PROPERTY STRINGS rows contiguous)
if(NOT ILLIXR_GEMMINI_PACKING MATCHES "^(scalar|rvv)$" OR NOT ILLIXR_GEMMINI_PACKING_TRAVERSAL MATCHES "^(rows|contiguous)$")
  message(FATAL_ERROR "Invalid Gemmini packing selection")
endif()
target_compile_definitions(app PRIVATE ILLIXR_GEMMINI_PACKING="${ILLIXR_GEMMINI_PACKING}")
set(ILLIXR_LINALG_BACKEND "eigen" CACHE STRING "eigen, openblas_scalar, openblas_rvv or openblas_gemmini_fp32")
set_property(CACHE ILLIXR_LINALG_BACKEND PROPERTY STRINGS eigen openblas_scalar openblas_rvv openblas_gemmini_fp32)
if(NOT ILLIXR_LINALG_BACKEND MATCHES "^(eigen|openblas_scalar|openblas_rvv|openblas_gemmini_fp32)$")
  message(FATAL_ERROR "Invalid ILLIXR_LINALG_BACKEND")
endif()
if(ILLIXR_GEMMINI_PACKING STREQUAL "rvv" AND NOT ILLIXR_LINALG_BACKEND STREQUAL "openblas_gemmini_fp32")
  message(FATAL_ERROR "RVV Gemmini packing requires the Gemmini backend")
endif()
add_compile_definitions(ILLIXR_LINALG_BACKEND="${ILLIXR_LINALG_BACKEND}")
target_sources(app PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../src/blas_backend.cpp)
if(NOT ILLIXR_LINALG_BACKEND STREQUAL "eigen")
  target_sources(app PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../src/blas_reference.cpp)
  set(ILLIXR_OPENBLAS_ARCHIVE "" CACHE FILEPATH "Pinned embedded OpenBLAS archive")
  if(NOT EXISTS "${ILLIXR_OPENBLAS_ARCHIVE}")
    message(FATAL_ERROR "Build OpenBLAS with scripts/build_openblas.py and set ILLIXR_OPENBLAS_ARCHIVE")
  endif()
  get_filename_component(blas_lib_dir "${ILLIXR_OPENBLAS_ARCHIVE}" DIRECTORY)
  file(READ "${blas_lib_dir}/../manifest.json" blas_manifest)
  string(JSON blas_backend GET "${blas_manifest}" backend)
  string(JSON blas_revision GET "${blas_manifest}" revision)
  string(JSON blas_expected_hash GET "${blas_manifest}" sha256)
  file(SHA256 "${ILLIXR_OPENBLAS_ARCHIVE}" blas_actual_hash)
  if(NOT blas_backend STREQUAL ILLIXR_LINALG_BACKEND OR
     NOT blas_revision STREQUAL "6d12fcab91ebf4de5eb23c1218727d2551b8635e" OR
     NOT blas_expected_hash STREQUAL blas_actual_hash)
    message(FATAL_ERROR "OpenBLAS archive provenance mismatch")
  endif()
  add_compile_definitions(EIGEN_USE_BLAS=1 ILLIXR_USE_OPENBLAS=1)
  target_link_libraries(app PRIVATE "${ILLIXR_OPENBLAS_ARCHIVE}")
  foreach(precision d s)
    foreach(operation gemm gemv trmm trmv trsm axpy)
      zephyr_ld_options("-Wl,--wrap=${precision}${operation}_")
    endforeach()
  endforeach()
  if(ILLIXR_LINALG_BACKEND MATCHES "^openblas_(rvv|gemmini_fp32)$" AND NOT CONFIG_RISCV_ISA_EXT_V)
    message(FATAL_ERROR "RVV OpenBLAS requires vector context support")
  endif()
  if(ILLIXR_LINALG_BACKEND MATCHES "^openblas_(rvv|gemmini_fp32)$")
    add_compile_definitions(ILLIXR_USE_RVV_BLAS=1)
    foreach(kernel dgemm_kernel dgemv_n dgemv_t)
      zephyr_ld_options("-Wl,--wrap=${kernel}")
    endforeach()
  endif()
  if(ILLIXR_LINALG_BACKEND STREQUAL "openblas_gemmini_fp32")
    if(CONFIG_SMP AND NOT CONFIG_SCHED_CPU_MASK)
      message(FATAL_ERROR "Gemmini requires hart-zero worker affinity")
    endif()
    string(JSON gemmini_include GET "${blas_manifest}" gemmini_include)
    string(JSON params_expected GET "${blas_manifest}" gemmini_params_sha256)
    file(SHA256 "${gemmini_include}/gemmini/gemmini_params.h" params_actual)
    if(NOT params_expected STREQUAL params_actual)
      message(FATAL_ERROR "Gemmini hardware header identity mismatch")
    endif()
    if(ILLIXR_GEMMINI_PACKING STREQUAL "rvv")
      include(${CMAKE_CURRENT_LIST_DIR}/illixr_rvv_packing.cmake)
      illixr_add_rvv_packing(app)
      target_compile_definitions(app PRIVATE ILLIXR_GEMMINI_PACKING_RVV=1)
      if(ILLIXR_GEMMINI_PACKING_TRAVERSAL STREQUAL "contiguous")
        target_compile_definitions(app PRIVATE ILLIXR_GEMMINI_PACKING_CONTIGUOUS=1)
      endif()
    endif()
    target_include_directories(app PRIVATE "${gemmini_include}")
    add_compile_definitions(ILLIXR_USE_GEMMINI_BLAS=1)
    target_sources(app PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../src/gemmini_backend.cpp
                               ${CMAKE_CURRENT_LIST_DIR}/../src/gemmini_selftest.cpp
                               ${CMAKE_CURRENT_LIST_DIR}/../tests/gemmini/edge_cases.cpp)
  endif()
endif()
if(CONFIG_RISCV_ISA_EXT_V)
  target_sources(app PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../src/vector_check.cpp
                             ${CMAKE_CURRENT_LIST_DIR}/../src/vector_check.S)
endif()
